server:
  port: 8080

spring:
  application:
    name: healthflow-intake-service

  datasource:
    url: jdbc:postgresql://localhost:5432/healthflow
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{Correlation-ID}] [%thread] %logger{36} - %msg%n"


  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all #Producer asks Kafka to acknowledge the message only after the required in-sync replicas have acknowledged it.
      retries: 3
